### ISSUE TITLE
jpm sign failed with "Incorrect authentication credentials"

### ISSUE THREAD

**Issue by serv-inc** [mozilla/olympia#1109]
The command

    jpm -v sign --api-key 'user:xxxxxxxx:xxx' --api-secret xxxxxxxxxxxxxxxxxxxxxxxxx

failed with the error message 

> Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/%40addonname/versions/0.x.y/

Version is 1.0.4

The full verbose output: (addon and file names modified)

    JPM [info] binary set to /usr/bin/firefox  
    JPM [info] verbose set  
    JPM [info] Checking compatability bootstrap.js and install.rdf for xpi  
    Validating the manifest  
    JPM [info] Creating fallbacks if they are necessary..  
    Creating XPI  
    JPM [info] Creating XPI...  
    JPM [info] .jpmignore found  
    JPM [info] Adding: /path/to/file  
    [...]  
    JPM [info] Adding: /path/to/another_file  
    JPM [info] XPI created at /tmp/tmp-unsigned-xpi-25600yuqzFN3Alxa0/@addonname-0.x.y.xpi (121ms)  
    JPM [info] Removing fallbacks if they were necessary..  
    JPM [info] Creating updateRDF...  
    Created XPI at /tmp/tmp-unsigned-xpi-25600yuqzFN3Alxa0/@addonname-0.x.y.xpi  
    JPM [info] Created XPI for signing: /tmp/tmp-unsigned-xpi-25600yuqzFN3Alxa0/@addonname-0.x.y.xpi  
    JPM [debug] [API] -{ url: 'https://addons.mozilla.org/api/v3/addons/%40addonname/versions/0.x.y/',  
      formData:   
       { upload:   
          { _readableState: [Object],  
            readable: true,  
            domain: null,  
            _events: [Object],  
            _eventsCount: 1,  
            _maxListeners: undefined,  
            path: '/tmp/tmp-unsigned-xpi-25600yuqzFN3Alxa0/@addonname-0.x.y.xpi',  
            fd: null,  
            flags: 'r',  
            mode: 438,  
            start: undefined,  
            end: undefined,  
            autoClose: true,  
            pos: undefined } },  
      headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }  
    JPM [debug] [API] <- { headers:   
       { allow: 'GET, PUT, HEAD, OPTIONS',  
         'content-type': 'application/json',  
         date: 'Thu, 17 Dec 2015 10:17:23 GMT',  
         server: 'nginx',  
         'set-cookie': '<REDACTED>',  
         'strict-transport-security': 'max-age=31536000',  
         vary: 'Accept, X-Mobile, User-Agent',  
         'www-authenticate': 'JWT realm="api"',  
         'x-frame-options': 'DENY',  
         'content-length': '51',  
         connection: 'Close' },  
      response: { detail: 'Incorrect authentication credentials.' } }  
    JPM [error] FAIL  
    Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/%40addonname/versions/0.x.y/  
      
    status: 401  
    response: {"detail":"Incorrect authentication credentials."}  
    headers: {"allow":"GET, PUT, HEAD, OPTIONS","content-type":"application/json","date":"Thu, 17 Dec 2015 10:17:23 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Thu, 17-Dec-2015 10:17:38 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Accept, X-Mobile, User-Agent","www-authenticate":"JWT realm=\"api\"","x-frame-options":"DENY","content-length":"51","connection":"Close"}  
      
        at /usr/local/lib/node_modules/jpm/lib/amo-client.js:85:13  
        at tryCatchReject (/usr/local/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:845:30)  
        at runContinuation1 (/usr/local/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:804:4)  
        at Fulfilled.when (/usr/local/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:592:4)  
        at Pending.run (/usr/local/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:483:13)  
        at Scheduler._drain (/usr/local/lib/node_modules/jpm/node_modules/when/lib/Scheduler.js:62:19)  
        at Scheduler.drain (/usr/local/lib/node_modules/jpm/node_modules/when/lib/Scheduler.js:27:9)  
        at doNTCallback0 (node.js:417:9)  
        at process._tickCallback (node.js:346:13)

See also http://stackoverflow.com/questions/34332450/generating-signed-xpi-via-jpm-failed.

The params were copy-pasted. The online form signed the addon correctly.

**Comment by serv-inc** [comment]
Maybe this was related to issues #1071  and #1072. The clock was off, though by less than a minute. After the fix, it worked.
