### ISSUE TITLE
jpm sign error FAIL ECONNREFUSED

### ISSUE THREAD

**Issue by jjargot** [mozilla/olympia#1136]
Hello,

There is an issue with server connection when using 'jpm sign'
*My private addon* gets uploaded and successfully validated, BUT the resulting xpi file is empty.

The xpi file is listed in my account on the web site https://addons.mozilla.org/en-US/developers/addon/case-id-working-diorectory/versions/***
When I click on the link https://addons.mozilla.org/firefox/downloads/file/***/case_id_working_diorectory-1.0.1-fx+an.xpi?src=devhub
Firefox browser displays "Firefox can't establish a connection to the server at addons.cdn.mozilla.net."

 
$ jpm sign --api-key *** --api-secret *** 
Creating XPI
JPM [info] XPI created at /tmp/tmp-unsigned-xpi-4486jjgbs4KHlns1/@com-bonitasoft-support-firefox-addons-caseid-workingdirectory-1.0.1.xpi (35ms)
Created XPI at /tmp/tmp-unsigned-xpi-4486jjgbs4KHlns1/@com-bonitasoft-support-firefox-addons-caseid-workingdirectory-1.0.1.xpi
JPM [info] Created XPI for signing: /tmp/tmp-unsigned-xpi-4486jjgbs4KHlns1/@com-bonitasoft-support-firefox-addons-caseid-workingdirectory-1.0.1.xpi
Validating add-on [.............................................................................................................................................................................]
JPM [info] Validation results: https://addons.mozilla.org/en-US/developers/upload/1b79d4194baa42809da4348bf0da1468
Downloading signed files: ...JPM [error] FAIL
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

$   du *xpi
0	case_id_working_diorectory-1.0.1-fx+an.xpi

regards,
Jerome

**Comment by jjargot** [comment]
Hello there,

The addons.cdn.mozilla.net server is still refusing connection.

It works once the 23/12/2015 and I manage to validate and sign a first addon.
But my 3 other ones just get uploaded, validated and signed, and it fails to download the resulting xpi file because of the addons.cdn.mozilla.net server which refused connection.

It is failing either via my account either with the command line 'jpm sign'

Please let me know what to do.

regards,
Jerome

**Comment by jjargot** [comment]
Hello,

Issue solve. The addons.cdn.mozilla.net accept again the connections this morning and after a logout / login into https://addons.mozilla.org/en-US/developers/

Closing this one

regards,
Jerome
