### ISSUE TITLE
Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1363]
Following on from #1229 we found the issue why this add-on failed, adding this to the #1244 tracker. We found that the validation took 20 seconds:

```
   MySQL [addons_mozilla_org]> select created, modified from file_uploads where uuid = '9700c2853c6549c8be9432d81bf1e69a';
    +---------------------+---------------------+
    | created             | modified            |
    +---------------------+---------------------+
    | 2016-01-10 05:16:13 | 2016-01-10 05:16:35 |
    +---------------------+---------------------+
    1 row in set (0.01 sec)
```

But no version was created. Kibana showed this:

```
2016-01-10T13:47:27.000Z    OlympiaWebApp   http_app_addons     signing     INFO    getting specific upload for 10510: FoxTrick 0.16.1...
2016-01-10T13:31:23.000Z    OlympiaWebApp   http_app_addons     signing     INFO    getting specific upload for 10510: FoxTrick 0.16.1...
2016-01-10T13:23:19.000Z    OlympiaWebApp   http_app_addons     signing     INFO    getting specific upload for 10510: FoxTrick 0.16.1...
2016-01-10T13:19:17.000Z    OlympiaWebApp   http_app_addons     signing     INFO    getting specific upload for 10510: FoxTrick 0.16.1...
2016-01-10T13:17:15.000Z    OlympiaWebApp   http_app_addons     signing     INFO    getting specific upload for 10510: FoxTrick 0.16.1...
2016-01-10T13:16:35.000Z    OlympiaWebApp   http_app_addons     z.devhub.task   INFO    Creating version for 9700c2853c6549c8be9432d81bf1e...
2016-01-10T13:16:13.000Z    OlympiaWebApp   http_app_addons     z.devhub    INFO    FileUpload created: 9700c2853c6549c8be9432d81bf1e6...
```

We came to the conclusion that it was failing somewhere around here:

https://github.com/mozilla/olympia/blob/master/apps/versions/models.py#L132-L145

But couldn't find anything in the log. Jason found this in the syslogs, it wasn't in kibana or sentry:

```
Jan 10 13:18:47 ip-172-31-39-200 http_app_addons: [<anon>][None] z.addons:ERROR Could not save version changes current: 0.16.11.205 to 0.16.11.205, latest: 0.16.11.205 to 0.16.11.206 for addon 10510: FoxTrick ((1205, 'Lock wait timeout exceeded; try restarting transaction')) :/data/olympia/apps/addons/models.py:754
Jan 10 13:18:47 ip-172-31-39-200 http_app_addons: [<anon>][None] z.task:ERROR Celery TASK exception: TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block. :/data/olympia/apps/amo/celery.py:46#012Traceback (most recent call last):#012  File "/data/olympia/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task#012    R = retval = fun(*args, **kwargs)#012  File "/data/olympia/venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__#012    return self.run(*args, **kwargs)#012  File "/data/olympia/apps/amo/decorators.py", line 168, in wrapper#012    return f(*args, **kw)#012  File "/data/olympia/apps/amo/decorators.py", line 155, in __call__#012    return self.f(*args, **kw)#012  File "/data/olympia/apps/devhub/tasks.py", line 71, in submit_file#012    create_version_for_upload(addon, file_)#012  File "/data/olympia/apps/amo/decorators.py", line 168, in wrapper#012    return f(*args, **kw)#012  File "/data/olympia/apps/amo/decorators.py", line 155, in __call__#012    return self.f(*args, **kw)#012  File "/data/olympia/apps/amo/decorators.py", line 258, in inner#012    return fn(*args, **kwargs)#012  File "/data/olympia/apps/devhub/tasks.py", line 90, in create_version_for_upload#012    version = Version.from_upload(file_, addon, [amo.PLATFORM_ALL.id])#012  File "/data/olympia/apps/versions/models.py", line 144, in from_upload#012    source=source#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create#012    return self.get_queryset().create(**kwargs)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create#012    obj.save(force_insert=True, using=self.db)#012  File "/data/olympia/apps/versions/models.py", line 126, in save#012    super(Version, self).save(*args, **kw)#012  File "/data/olympia/apps/amo/models.py", line 290, in save#012    result = super(OnChangeMixin, self).save(*args, **kw)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save#012    force_update=force_update, update_fields=update_fields)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base#012    update_fields=update_fields, raw=raw, using=using)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send#012    response = receiver(signal=self, sender=sender, **named)#012  File "/data/olympia/apps/versions/models.py", line 582, in update_incompatible_versions#012    if not instance.addon.reload().type == amo.ADDON_EXTENSION:#012  File "/data/olympia/apps/amo/models.py", line 376, in reload#012    from_db = self.__class__.get_unfiltered_manager().get(pk=self.pk)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get#012    return self.get_queryset().get(*args, **kwargs)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get#012    num = len(clone)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__#012    self._fetch_all()#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all#012    self._result_cache = list(self.iterator())#012  File "/data/olympia/venv/src/django-cache-machine/caching/base.py", line 146, in iterator#012    return iter(iterator())#012  File "/data/olympia/venv/src/django-queryset-transform/queryset_transform/__init__.py", line 20, in iterator#012    results = list(result_iter)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator#012    for row in compiler.results_iter():#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter#012    for rows in self.execute_sql(MULTI):#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql#012    cursor.execute(sql, params)#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/backends/util.py", line 47, in execute#012    self.db.validate_no_broken_transaction()#012  File "/data/olympia/venv/lib/python2.7/site-packages/django/db/backends/__init__.py", line 372, in validate_no_broken_transaction#012    "An error occurred in the current transaction. You can't "#012TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by andymckay** [comment]
This could in theory happen, but this particular case is going to be solved by fixing cache machine and stopping those long invalidation cycles.
