### ISSUE TITLE
Receipt error in logs

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#922]
The logs are full of this:

	Type: <type 'exceptions.UnicodeDecodeError'>, 'utf8' codec can't decode byte 0xae in position 19: invalid start byte. Data:  :./services/utils.py:143#012Traceback (most recent call last):#012  File "./services/theme_update.py", line 219, in application#012    output = update.get_json()#012  File "./services/theme_update.py", line 160, in get_json#012    return json.dumps(data)#012  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps#012    return _default_encoder.encode(obj)#012  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode#012    chunks = self.iterencode(o, _one_shot=True)#012  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode#012    return _iterencode(o, 0)#012UnicodeDecodeError: 'utf8' codec can't decode byte 0xae in position 19: invalid start byte

from z.receipt.

**Comment by andymckay** [comment]
By the way, they don't show up in sentry.

**Comment by andymckay** [comment]
@jasonthomas fixed the logs so it's not z.receipt.

**Comment by andymckay** [comment]
@magopian got this in #1090
